name: Release
on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Image
        run: docker build -t app:latest ./

      - name: "Say Hello"
        id: test-data
        run: echo "::set-output name=value::$(docker container run app:latest hello world)"

      - uses: nick-fields/assert-action@v1
        with:
          expected: hello world
          actual: ${{ steps.test-data.outputs.value }}
          comparison: exact

      - name: Test Execution
        run: |
          docker run --name my-container -d captainissou42/containerdevops:GarciaAdrien
          docker exec my-container sh -c "your-test-command" || exit 1

      - name: Stop Container
        run: docker stop my-container

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: GarciaAdrien
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push if on `main`
        uses: docker/build-push-action@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          push: true
          context: ./
          tags: captainissou42/containerdevops:GarciaAdrien
